package com.openyogaland.denis.dreamdiary.enumeration

enum class
CalendarDateType
{
  ORDINARY,
  SELECTED,
  CURRENT,
  
  ORDINARY_WITH_DAY,
  SELECTED_WITH_DAY,
  CURRENT_WITH_DAY,
  
  ORDINARY_WITH_DREAM,
  SELECTED_WITH_DREAM,
  CURRENT_WITH_DREAM,
  
  ORDINARY_WITH_DAY_AND_DREAM,
  SELECTED_WITH_DAY_AND_DREAM,
  CURRENT_WITH_DAY_AND_DREAM,
  
  OTHER_MONTH
}